export const CHANGE_MAP_CENTER = 'CHANGE_MAP_CENTER';

export const SET_MARKER_ADDRESS = 'SET_MARKER_ADDRESS';
export const SET_MARKER_COORDS = 'SET_MARKER_COORDS';

export const CHANGE_MARKER_ORDER = 'CHANGE_MARKER_ORDER';

export const ADD_MARKER = 'ADD_MARKER';
export const REMOVE_MARKER = 'REMOVE_MARKER';
